language: csharp
sudo: required
dist: xenial

mono: none
dotnet: 2.2

solution: ValveKeyValue/ValveKeyValue.sln

notifications:
  email: false

install:
  - dotnet restore ValveKeyValue/ValveKeyValue.sln
script:
  - dotnet build ValveKeyValue/ValveKeyValue.sln --configuration Release
  - dotnet test --configuration Release ValveKeyValue/ValveKeyValue.Test/ValveKeyValue.Test.csproj
